Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository.
Change-Id: I0ad13d2cfdf245c4106bad751f1f74c9e6f3e6f6